on:
  push:
    branches: [main]
name: CI
jobs:
  setup-android:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master
      - name: Setup middleware dependency
        env:
          token_secret: ${{ secrets.GITHUB_TOKEN }}
          user_secret: ${{ github.actor }}
          amplitude_secret: ${{ secrets.AMPLITUDE_KEY }}
          amplitude_secret_debug: ${{ secrets.AMPLITUDE_KEY }}
          sentry_dsn_secret: ${{ secrets.SENTRY_DSN }}
        run: ./middleware2.sh $token_secret $user_secret $amplitude_secret $amplitude_secret_debug $sentry_dsn_secret

      - name: Run unit tests. Full mode.
        run: ./gradlew build test -Dpre-dex=false -q
